receivers:
  otlp:
    protocols:
      http:
      grpc:
exporters:
  emptyexporter: {}
  prometheus:
    endpoint: "0.0.0.0:8889"
  jaeger:
    endpoint: "http://localhost:14250"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [emptyexporter, jaeger]
    metrics:
      receivers: [otlp]
      exporters: [emptyexporter, prometheus]
    logs:
      receivers: [otlp]
      exporters: [emptyexporter]

